version: "3"
services:
  api-gateway:
    container_name: wazzilla-api-gateway
    build: "./api-gateway"
    depends_on:
      - users-service
      - notes-service
    environment:
      USERS_SERVICE_URI: ${USERS_SERVICE_URI}
      NOTES_SERVICE_URI: ${NOTES_SERVICE_URI}
      PORT: ${API_GATEWAY_PORT}
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    volumes:
      - ./api-gateway:/opt/app

  users-service:
    container_name: wazzilla-users-service
    build: "./users-service"
    depends_on:
      - users-service-db
    environment:
      USERS_DB_URI: ${USERS_DB_URI}
      USERS_SERVICE_PORT: ${USERS_SERVICE_PORT}
      USER_SESSION_EXPIRY_HOURS: ${USER_SESSION_EXPIRY_HOURS}
    volumes:
      - ./users-service:/opt/app
    ports:
      - "${USERS_SERVICE_PORT}:${USERS_SERVICE_PORT}"

  users-service-db:
    container_name: wazzilla-users-service-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    image: mysql/mysql-server:5.7.21
    ports:
      - 0.0.0.0:${USERS_SERVICE_DB_PORT}:3306

  notes-service:
    container_name: wazzilla-notes-service
    build: "./notes-service"
    depends_on:
      - notes-service-db
    environment:
      NOTES_DB_URI: ${NOTES_DB_URI}
      NOTES_SERVICE_PORT: ${NOTES_SERVICE_PORT}
      LIMIT_NOTES_FOR_PAGE: ${LIMIT_NOTES_FOR_PAGE}
    ports:
      - "${NOTES_SERVICE_PORT}:${NOTES_SERVICE_PORT}"
    volumes:
      - ./notes-service:/opt/app

  notes-service-db:
    container_name: wazzilla-notes-service-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    image: mysql/mysql-server:5.7.21
    ports:
      - 0.0.0.0:${NOTES_SERVICE_DB_PORT}:3306

  test-db:
    container_name: wazzilla-test-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    image: mysql/mysql-server:5.7.21
    ports:
      - 0.0.0.0:${TEST_DB_PORT}:3306
