name: WAZZILLA
env:
  APPLICATION_NAME: "Wazzilla"
  DEPLOY_PACKAGE_NAME: "wazzilla-ver-${{ github.sha }}"
  SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
  ARGS: "-rltgoDzvO"
  SOURCE: "./"
  REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
  REMOTE_USER: ${{ secrets.REMOTE_USER }}
  TARGET: ${{ secrets.REMOTE_TARGET }}
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone my repo
      - uses: actions/checkout@v2

      - name: Create zip deployment package
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.1

      - name: Print Happy Message
        run: echo "${{ env.APPLICATION_NAME }} success build"
